mod.id=ofa-api
mod.name=One For All API
mod.description=API for creating mods that are compatible with One For All.
mod.version=0.1.0

deps.minecraft.dependency=[VERSIONED]
deps.fabric.loader=0.16.10
deps.fabric.loader.dependency=[VERSIONED]
deps.fabric.yarn=[VERSIONED]
deps.fabric.yarn.dependency=[VERSIONED]
deps.fabric.api=[VERSIONED]
deps.fabric.api.dependency=[VERSIONED]